name: 'Build with Expo'
description: 'React-native build'
inputs:
   expo-cli-username:
     description: 'The Expo CLI username'
     required: true
     default: '${{ secrets.EXPO_CLI_USERNAME }}'
   expo-cli-password:
     description: 'The Expo CLI password'
     required: true
     default: '${{ secrets.EXPO_CLI_PASSWORD }}'
   expo-version:
     description: 'The Expo version'
     required: false
     default: '4.x'
   node-version:
     description: 'The NodeJs version'
     required: false
     default: '14.x'
   platform:
     description: 'android | ios'
     required: true
     default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
    - uses: expo/expo-github-action@v5
      with:
        expo-version: ${{ inputs.expo-version }}
        expo-username: ${{ inputs.expo-cli-userame }}
        expo-password: ${{ inputs.expo-cli-password }}
    - run: yarn install
    - name: Build (Android)
      if: ${{ inputs.platform }} == "android"
      run: expo build:${{ inputs.platform }} --type app-bundle
    - name: Build (IOS)
      if: ${{ inputs.platform }} == "ios"
      run: expo build:${{ inputs.platform }}