name: Manual Build
on:
  workflow_dispatch:
    inputs:
      expo-cli-username:
         description: 'The Expo CLI username'
         required: true
         default: ''
      expo-cli-password:
         description: 'The Expo CLI password'
         required: true
         default: ''
      platform:
        description: 'android or ios'
        required: true
        default: ''
jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}
      - uses: expo/expo-github-action@v5
        with:
          expo-version: ${{ inputs.expo-version }}
          expo-username: ${{ inputs.expo-cli-userame }}
          expo-password: ${{ inputs.expo-cli-password }}
      - run: yarn install
      - name: Build (Android)
        if: ${{ inputs.platform }} == "android"
        run: expo build:${{ inputs.platform }} --type app-bundle
      - name: Build (IOS)
        if: ${{ inputs.platform }} == "ios"
        run: expo build:${{ inputs.platform }}


